import {notFound} from 'next/navigation';
import { Inder } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar';
import LanguageSelection from './components/LanguageSelection';

const inter = Inder({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'hi'];

export default function RootLayout({ children, params: {locale} }) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>      
      <body className={inter.className}>
        <LanguageSelection/>
        <NavBar lang={locale}/>
        {children}
      </body>
    </html>
  )
}
